apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-gxs6
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0035-tenant/tkrw-pr712-0075-0035-app/devfile-sample-gxs6@sha256:95612c04935aefdf6e8272a05d6bd842cdbe199518cbda8a25b201eeaf1a336d
        name: my-nodejs
        resources: {}
status: {}
